TITLE ASKISI4
KODIKAS SEGMENT PUBLIC
ASSUME CS:KODIKAS, DS:DEDOMENA, SS:SOROS
    KYRIO PROC NEAR
                    ; OI 2 PARAKATO ENTOLES APOKATHISTOYN THN TIMH TOY DS.
	    MOV AX,DEDOMENA 
	    MOV DS,AX

KLISI:	
        MOV COUNT,0    
	    CALL YPO1
	    CALL YPO1
	    CALL YPO1
	    ;opote twra exw sthn monada tis monades p ebale sthn dekada tis dekades p ebale kai sthn ekatontada ts ekatontades p ebale
	    ;arkei na kanw  ekatontades*100 meta dekades*10 ....meta->(ekatontades*100 meta dekades*10)+monades
	    
	    
	    SUB EKATONTADA,48;GIATI DEN THELW THN ASCII TIMH THELW TON ARITHMO AUTO KATHE AUTO
	    SUB DEKADA,48
	    SUB MONADA,48
	    
	    
	     
	    MOV AX,0
	    MOV AL,EKATONTADA  ;ETSI KSERW OTI O AX EXEI OTI EXEI O AL
	    MUL EKATO;pollaplasiazw to periexomeno tou al me to 100
	    MOV BX,AX;metakinw to apotelesma ston AX GIA PRWSORINH APOTHIKEUSH
	    MOV AX,0
	    MOV AL,DEKADA ;ETSI KSERW OTI O AX EXEI OTI EXEI MESA O AL
	    MUL DEKA ;TO APOTELESMA TOU POSES DEKADES EXW APOTHIKEUMENO STON AX
	    ADD BX,AX ;PROSTHETW EKATONTADES+DEKADES ...ARKEI META NA PROSTHESW TIS MONADES
	    MOV AX,0
	    MOV AL,MONADA 
	    ADD BX,AX
	    
	    MOV AX,0
	    
	    CMP BX,255
	    JA KLISI
	    
	    CMP BX,32
	    JBE MHEKTYP
	    ;AN DEN EINAI MH EKTUPOSIMOS OUTE PANW APO 255 H ASCII TIMH TOU TOTE SHMAINEI PWS MPORW NA TON EKTYPWSW 
	    ;KAI TO PERIEXOMENO OLWN TWN PRAKSEWN BRISKETAI STON BL..EPEIDH ASCII TIMH <=255 ...O BL EXEI 8 BIT..2 STHN OGDOH KANEI 256(0-255)
	    ;ARA TO PERIEXOMENO TOU BX EINAI PRAKTIKA O BL
	    MOV DL,BL
	    MOV AH,2
	    INT 21H   ;AFOU FTANW STO SHMEIO NA TON EKTYPWSW..SHMAINEI OTI DEN EINAI MH EKTYPOSIMOS DLD <32 ARA EINAI KATW APO 255 KAI PANW APO 32
	    
	    CMP BL,64
	    JBE ARITH_SYM
	    ;ALLIWS AN EINAI PANW APO 64
	    
	    CMP BL,90  ;KEFALAIA GRAMMATA
	    JBE GRAMMA
	    
	    CMP BL,96  ; XARAKTHRES [ WS '
	    JBE ARITH_SYM 
	    
	    CMP BL,122 ;AN EINAI PANW APO 96 KAI KATW APO 122 SHMAINEI OTI EXW MIKRO GRAMMA
	    JBE GRAMMA   ;TA YPOLOIPA EINAI REGIONAL..PANW APO TA MIKRA GRAMMATA DHLADH
	    
	    LEA DX,REG
	    MOV AH,9
	    INT 21H
	    JMP EXIT
	    
	    
	    
ARITH_SYM:LEA DX,AR_SUM
          MOV AH,9
          INT 21H
          JMP EXIT
          
GRAMMA:	  LEA DX,GRAM
          MOV AH,9
          INT 21H
          JMP EXIT
	    
	    
MHEKTYP:LEA DX,OXI_EKTYPOSIMOS
        MOV AH,9
        INT 21H 
	     
EXIT:	MOV AH,4CH	
    	INT 21H  
    KYRIO ENDP 	  
    	  
    	  
    YPO1 PROC
    LEA DX,PROTROPI
    MOV AH,9
    INT 21H
    JMP EIS

BEEP:LEA DX,WRONG
     MOV AH,9
     INT 21H

     MOV DL,7
     MOV AH,2
     INT 21H
    
EIS:MOV AH,8
    INT 21H
    
    CMP AL,'0'
    JB EIS
    
    CMP AL,'9'
    JA EIS  
    
    CMP COUNT,1;TOTE PAEI N PEI OTI BAZEI NOJUMERO 2H FORA NA TO BALEI STH DEKADA
    JE DEK
    
    CMP COUNT,2;TOTE PAEI N PEI OTI BAZEI NOJUMERO 2H FORA NA TO BALEI STHN EKATONTADA
    JE MONAD
    ;ALLIWS PAEI NA PEI OTI BAZEI PRWTH FORA..AS TO BALEI STHN MONADA
EKAT:MOV EKATONTADA,AL
    INC COUNT
    JMP EMF
    
DEK:MOV DEKADA,AL
    INC COUNT
    JMP EMF
              
MONAD:MOV MONADA,AL
        INC COUNT
     
EMF: MOV DL,AL
     MOV AH,2
     INT 21H   
            
RETURN:RET        
    YPO1 ENDP        	
    	  
	    
	    KODIKAS ENDS

DEDOMENA SEGMENT    
                    
    PROTROPI DB 'Eisagete keimeno:  $';
	OXI_EKTYPOSIMOS DB 10,13,'Eisagete ena charactira: $' ; To minima pou tha emfanistei
	REG DB 10,13,'REGIONAL XARAKTHRAS$'; 
	MH_EKT DB 10,13,'OXI EKTYPOSIMOS$'
	AR_SUM DB 10,13, 'SYMBOLO / ARITHMOS$'
	GRAM DB 10,13,'GRAMMA$'
	WRONG DB 10,13,'LATHOS EISAGWGH EISAGETE NOUMERO 0-9 $'                                      
	
	
	EKATONTADA DB 0
	DEKADA DB 0
	MONADA DB 0
	COUNT DB 0  ;GIA NA BLEPW TI EISAGEI KATHE FORA
	EKATO DB 100;TA THELOUME GIA TO POLLAPLASIASMO WSTE N BGALW EKATONTADES
	DEKA DB 10;TA THELOUME GIA TO POLLAPLASIASMO WSTE N BGALW DEKADES
							
DEDOMENA ENDS

	END KYRIO